"""API schemas for BrainScore.

Extension fields (`user_id`, `model_version`, `raw_predictions_uri`) are
baked in from Stage 1 even though they are populated or required only in
later stages — see IMPLEMENTATION_PLAN.md §6.4. Adding optional fields later
is free; threading them through every layer in Stage 4 is not.

`Moment` and `Event` live here (rather than in services/) because they're
part of the public BrainReport surface — the frontend types against them
and the §6.2 one-way-dep rule says core/ doesn't import from services/.
The services/suggestions module re-exports them for backward import paths.
"""

from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field

from .scoring.goals import Goal


class AnalyzeRequest(BaseModel):
    content_url: str
    content_type: Literal["video", "image", "text"]
    goal: Goal
    user_id: str | None = None
    request_id: str = Field(default_factory=lambda: str(uuid4()))


class Event(BaseModel):
    """A type-tagged span of input content with optional text.

    Mirrors what tribev2 emits in `model.get_events_dataframe()`. The GPU
    worker serializes these and the API decodes them so the suggestion
    engine can explain WHEN problems happen and WHAT was on screen.
    """

    type: Literal["Word", "Sentence", "Audio", "Video", "Unknown"]
    start_s: float
    duration_s: float
    text: str | None = None


class Moment(BaseModel):
    """A window where a brain region's per-timestep score crossed a threshold.

    Dips identify *where* a content problem happens; peaks identify
    strengths. Both are pre-computed in api/predict.py so the Stage 2
    suggestion engine can build timestamp-anchored prompts and the
    frontend can render dip/peak chips on each region card.
    """

    region: str
    type: Literal["dip", "peak"]
    start_s: float
    end_s: float
    avg_score: float
    context: str = ""
    events: list[Event] = []


class Suggestion(BaseModel):
    """One actionable diagnosis attached to a region in the BrainReport.

    Generated by the Stage 2 suggestion engine
    (services.suggestions.diagnose). Each suggestion is anchored to a
    region + (optional) timestamp window and includes a short fix the
    creator can act on. Stage 2 also matches each suggestion to high-
    scoring reference ads — those land in `examples` once
    services.examples.library is wired in.
    """

    region: str
    priority: Literal["critical", "important", "minor"]
    title: str
    fix: str
    why: str
    timestamp_start_s: float | None = None
    timestamp_end_s: float | None = None
    examples: list[str] = []  # reference ad names; full lookup in services.examples


class BrainReport(BaseModel):
    request_id: str
    region_scores: dict[str, float]
    overall_score: float
    goal: Goal
    user_id: str | None = None
    model_version: str
    raw_predictions_uri: str | None = None
    brain_image_b64: str | None = None
    elapsed_ms: int
    # Stage 2 fields — populated when temporal pipeline runs (always today;
    # keeping defaults so existing JSON consumers tolerate older payloads).
    region_timeseries: dict[str, list[float]] | None = None
    moments: list[Moment] = []
    suggestions: list[Suggestion] = []
