"""Register a fixture as a Stage 2 reference ad.

Computes the BrainReport (region scores + per-goal overall scores) from
the (T, 20484) prediction array, then writes a manifest to
data/reference_ads/<name>.json. The Stage 2 suggestion engine queries
these manifests to surface high-scoring examples for whichever region
the user's content scored low in.

A reference ad can be a video, a single-image post, or a carousel —
they all reduce to the same `(T, 20484)` prediction tensor. The
optional `--content-type` flag tags the manifest so the suggestion
engine can prefer apples-to-apples examples (post → post, video →
video).

Usage:

    # Video reference (sintel — the original)
    uv run python scripts/register_reference_ad.py \\
        tests/fixtures/golden_pred_sintel_T53.npy \\
        --name sintel_trailer \\
        --display-name "Sintel Trailer" \\
        --content-type video \\
        --source-url https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4 \\
        --thumbnail-url https://i.imgur.com/sintel-thumb.jpg \\
        --description "Blender Foundation open-movie trailer, fantasy animation" \\
        --tags fantasy,trailer,animation,cinematic \\
        --license "CC BY 3.0"

    # Post reference (Pepsi Cream Soda still + caption)
    uv run python scripts/register_reference_ad.py \\
        tests/fixtures/golden_pred_post_<hash>_T6.npy \\
        --name pepsi_cream_soda \\
        --display-name "Pepsi Cream Soda Reveal" \\
        --content-type post \\
        --source-url https://instagram.com/p/... \\
        --thumbnail-url https://cdn.cortyze.com/refs/pepsi-cream-soda.jpg \\
        --caption "Treat yourself! Pepsi Cola Cream Soda is here to stay." \\
        --description "Static product post — soda can with ice cream cone, blue background" \\
        --tags beverage,cpg,product-shot,still-life,blue \\
        --license "Fair use — Pepsi Co"

After registering, restart the API so the in-process library cache reloads,
or call services.examples.library.reload() in tests.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

from core.atlas.mapper import aggregate
from core.scoring.goals import Goal, overall_score
from core.scoring.normalize import normalize


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "predictions_path",
        type=Path,
        help="Path to the .npy file containing (T, 20484) predictions. "
        "Generated by scripts/build_fixture.py (videos) or "
        "scripts/build_post_fixture.py (posts).",
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Slug used as filename and lookup key. lowercase_with_underscores.",
    )
    parser.add_argument("--display-name", help="Human-readable title (default: name)")
    parser.add_argument("--source-url", required=True)
    parser.add_argument(
        "--thumbnail-url",
        default="",
        help="Public URL to a 16:9 still preview, shown in the SuggestionCard "
        "expand UI. For videos, a representative frame; for posts, the post "
        "image itself; for carousels, the first image.",
    )
    parser.add_argument("--description", default="")
    parser.add_argument(
        "--caption",
        default="",
        help="Original caption / copy. Fed into the lexical-relevance ranker, "
        "so a user with a similarly-themed caption sees this ad first.",
    )
    parser.add_argument(
        "--tags",
        default="",
        help="Comma-separated category keywords (e.g. 'beverage,cpg,still-life'). "
        "Boost ranking when the user's caption / brand-context shares these.",
    )
    parser.add_argument(
        "--content-type",
        choices=["video", "post", "image"],
        default="video",
        help="Shape of the source content. Defaults to video for backward "
        "compat with manifests written before this flag existed.",
    )
    parser.add_argument("--license", default="")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing manifest with the same --name.",
    )
    args = parser.parse_args()

    if not args.predictions_path.exists():
        print(f"ERROR: {args.predictions_path} not found", file=sys.stderr)
        return 1

    preds = np.load(args.predictions_path)
    if preds.ndim != 2 or preds.shape[1] != 20484:
        print(f"ERROR: unexpected shape {preds.shape}", file=sys.stderr)
        return 1

    region_scores = normalize(aggregate(preds))
    overall_by_goal = {g.value: overall_score(region_scores, g) for g in Goal}

    repo_root = Path(__file__).resolve().parent.parent
    out_dir = repo_root / "data" / "reference_ads"
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        rel_path = args.predictions_path.resolve().relative_to(repo_root)
    except ValueError:
        rel_path = args.predictions_path.resolve()

    tags = [t.strip() for t in args.tags.split(",") if t.strip()]

    manifest = {
        "name": args.name,
        "display_name": args.display_name or args.name,
        "source_url": args.source_url,
        "thumbnail_url": args.thumbnail_url or None,
        "description": args.description,
        "caption": args.caption,
        "tags": tags,
        "content_type": args.content_type,
        "license": args.license,
        "predictions_path": str(rel_path),
        "predictions_shape": list(preds.shape),
        "region_scores": region_scores,
        "overall_by_goal": overall_by_goal,
        "registered_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    out_path = out_dir / f"{args.name}.json"
    if out_path.exists() and not args.force:
        print(
            f"ERROR: {out_path.relative_to(repo_root)} already exists. "
            "Pass --force to overwrite, or pick a different --name.",
            file=sys.stderr,
        )
        return 1
    out_path.write_text(json.dumps(manifest, indent=2) + "\n")

    top_region = max(region_scores, key=region_scores.get)
    top_goal = max(overall_by_goal, key=overall_by_goal.get)
    print(f"Registered {args.name} → {out_path.relative_to(repo_root)}")
    print(f"  Content type: {args.content_type}")
    print(f"  Top region:   {top_region} ({region_scores[top_region]:.1f})")
    print(f"  Top goal:     {top_goal} ({overall_by_goal[top_goal]:.1f})")
    if tags:
        print(f"  Tags:         {', '.join(tags)}")
    if not args.thumbnail_url:
        print(
            "  ⚠️  No --thumbnail-url provided. The SuggestionCard will fall back "
            "to a text-only example. Add one for a richer card.",
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
